# Generated by Django 5.1 on 2024-09-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0002_delete_usuario_alter_equipamento_ca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='validade',
            field=models.DateField(),
        ),
    ]
