# Generated by Django 5.1 on 2024-09-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0004_alter_equipamento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='validade',
            field=models.DateField(),
        ),
    ]
