# Generated by Django 5.1 on 2024-09-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0005_alter_equipamento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='validade',
            field=models.TextField(max_length=100),
        ),
    ]
