# Generated by Django 5.1 on 2024-10-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0006_alter_equipamento_validade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('matricula', models.IntegerField(max_length=100)),
            ],
        ),
    ]
