# Generated by Django 5.1 on 2024-10-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0007_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='validade',
            field=models.DateField(),
        ),
    ]
