# Generated by Django 5.1 on 2024-10-14 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0008_alter_equipamento_validade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('previsao_devolucao', models.DateField()),
                ('condicoes', models.CharField(max_length=100)),
                ('data_devolucao', models.DateField()),
                ('observacao', models.CharField(max_length=100)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi.equipamento')),
            ],
        ),
    ]
