# Generated by Django 5.1 on 2024-10-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0009_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='status',
            field=models.CharField(default='Ativo', max_length=100),
        ),
    ]
