# Generated by Django 5.1 on 2024-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0010_registro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
