# Generated by Django 5.1 on 2024-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0012_alter_registro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_devolucao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='observacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
